### ISSUE TITLE
web-worker type export

### ISSUE THREAD

**Issue by henrik-d** [bugsnag/bugsnag-js#1951]
### Describe the bug
I'm using vite and get the following error in my typescript react project:
`./node_modules/@bugsnag/web-worker/types/notifier.ts(17,10): error TS1205: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.`

### Environment
* Bugsnag version:   @bugsnag/web-worker": "^7.20.1"

**Comment by mclack** [comment]
Hi @henrik-d, I have attempted to reproduce the error you are seeing but have been unable to so far. Can I first confirm that you are definitely using [bugsnag/web-worker](https://www.npmjs.com/package/@bugsnag/web-worker) within a web worker and not in another part of your app?

Can I also confirm how you are installing and using BugSnag? I.e: what commands did you run and are you using an import statement or require statement?

Any reproduction steps you can provide would be really useful. I think it would be especially handy to see your tsconfig.json file, but if you’re willing to share the files where you are attempting to configure and use BugSnag that would be great. You can write into [support@bugsnag.com](mailto:support@bugsnag.com) if there is anything you do not want to share on this public thread.

**Comment by mclack** [comment]
Hi @henrik-d, thanks for that extra info. We’ve realised the issue here is that the file is not currently named as a `.d.ts` file, which would mark it as a type declaration file. This also follows the convention set by our other notifier libraries.

We will rename this file and schedule the update for our next release. In the meantime, you can either rename the file to end in `.d.ts` or change `export { WorkerConfig }` to `export type { WorkerConfig }` as you previously mentioned.

Thank you for bringing this to our attention. We will post an update on this thread once the fix has been deployed.

**Comment by Danetag** [comment]
@mclack Hey there! The issue seems to be persistent for me. Is it something expected?

**Comment by mclack** [comment]
Hi @Danetag 

We haven't yet deployed any changes which cover this. Have you attempted the solutions as outlined above? I.e:

> you can either rename the file to end in .d.ts or change `export { WorkerConfig }` to `export type { WorkerConfig }`

**Comment by tizmagik** [comment]
Hi @mclack looks like this is still an issue in v8? Are there any blockers in getting this addressed? Thanks for your efforts 🙏

**Comment by clr182** [comment]
Hi @tizmagik 

This issue is still on our backlog. We will be sure to get round to it when priorities allow and update this thread with more information.

**Comment by hivokas** [comment]
Still happening :(
